# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.1

MagicComments/Encoding:
  EnforcedStyle: when_needed
  Enabled: true

MagicComments/FrozenStringLiteral:
  EnforcedStyle: always

Style/IndentHeredoc:
  EnforcedStyle: powerpack

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
