sudo: false
cache: bundler
language: ruby
dist: trusty
rvm:
  - jruby-9.2.0.0
  - jruby-head
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
env:
  global:
    - JRUBY_OPTS='--debug -J-Xmx1000M' # get more accurate coverage data in JRuby
    # Travis CI container has two cores, but Ruby can see 32 cores unfortunately.
    # See https://github.com/bbatsov/rubocop/pull/5719
    #     https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System
    - TEST_QUEUE_WORKERS=2
  matrix:
    - 'TASK=spec'
    - 'TASK=ascii_spec'
    - 'TASK=internal_investigation'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
before_install:
  - gem update --system
  - gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - ruby .travis.rb
addons:
  code_climate:
    repo_token: a11b66bfbb1acdf220d5cb317b2e945a986fd85adebe29a76d411ad6d74ec31f
