sudo: false

language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-2.2.10

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

script:
  - bundle exec rspec
  - bundle exec rubocop
