---

version: "{build}"

install:
  - set PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem update --no-document --system 2.7.8
  - gem install bundler --no-document --version="<2.0.0"
  - bundle install --jobs 3 --retry 3

build: off

# We are intentionally starting Rake a few times here, because we have seen some
# encoding issues when all tasks are run in just one process (`rake default`).
test_script:
  - bundle exec rake spec
  - bundle exec rake ascii_spec
  - bundle exec rake internal_investigation

environment:
  matrix:
    - ruby_version: '22'
    - ruby_version: 22-x64
    - ruby_version: '23'
    - ruby_version: 23-x64
    - ruby_version: '24'
    - ruby_version: 24-x64
    - ruby_version: '25'
    - ruby_version: 25-x64
