version: 2.1

jruby_env: &jruby_env
  # By default we have 2 CPUs and 4GB ram available
  # https://circleci.com/docs/2.0/configuration-reference/#resource_class
  JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"

common_env: &common_env
  # CircleCI container has two cores, but Ruby can see 32 cores. So we
  # configure test-queue.
  # See https://github.com/tmm1/test-queue#environment-variables
  TEST_QUEUE_WORKERS: 2

jobs:

  spec:
    parameters:
      image:
        type: string
    docker:
      - image: <<parameters.image>>
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/tmp
      - run: bundle install
      - run:
          name: Run specs
          command: |
            ./tmp/cc-test-reporter before-build
            COVERAGE=true bundle exec rake spec
            ./tmp/cc-test-reporter format-coverage --output tmp/codeclimate.$CIRCLE_JOB.json
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.*.json

  ascii_spec:
    parameters:
      image:
        type: string
    docker:
      - image: <<parameters.image>>
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake ascii_spec

  rubocop:
    parameters:
      image:
        type: string
    docker:
      - image: <<parameters.image>>
    environment:
      <<: *common_env
      <<: *jruby_env
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake internal_investigation
      - run:
          name: Check requiring libraries successfully
          # See https://github.com/rubocop-hq/rubocop/pull/4523#issuecomment-309136113
          command: |
            ruby -I lib -r bundler/setup -r rubocop -e 'exit 0'

  # Job for downloading the Code Climate test reporter
  cc-setup:
    docker:
      - image: circleci/ruby
    environment:
      <<: *common_env
    steps:
      - run:
          name: Download Code Climate test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  # Job for merging code coverage results and sending them to Code Climate
  cc-upload-coverage:
    docker:
      - image: circleci/ruby
        environment:
          CC_TEST_REPORTER_ID: a11b66bfbb1acdf220d5cb317b2e945a986fd85adebe29a76d411ad6d74ec31f
    environment:
      <<: *common_env
    steps:
      - attach_workspace:
          at: ~/project/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json --parts 5 --output tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage --input tmp/codeclimate.total.json

  # Miscellaneous tasks
  documentation-checks:
    docker:
      - image: circleci/ruby
    environment:
      <<: *common_env
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Check documentation syntax
          command: bundle exec rake documentation_syntax_check
      - run:
          name: Build documentation and check that manual files are in sync
          command: bundle exec rake generate_cops_documentation

workflows:
  version: 2
  build:
    jobs:
      - documentation-checks
      - cc-setup

      - spec:
          requires:
            - cc-setup
          matrix:
            parameters:
              image:
                - circleci/ruby:2.4
                - circleci/ruby:2.5
                - circleci/ruby:2.6
                - circleci/ruby:2.7
                - rubocophq/circleci-ruby-snapshot:latest # ruby-head (nightly snapshot build)
                - circleci/jruby:9.2

      - ascii_spec:
          matrix:
            parameters:
              image:
                - circleci/ruby:2.4
                - circleci/ruby:2.5
                - circleci/ruby:2.6
                - circleci/ruby:2.7
                - rubocophq/circleci-ruby-snapshot:latest # ruby-head (nightly snapshot build)
                - circleci/jruby:9.2

      - rubocop:
          matrix:
            parameters:
              image:
                - circleci/ruby:2.4
                - circleci/ruby:2.5
                - circleci/ruby:2.6
                - circleci/ruby:2.7
                - rubocophq/circleci-ruby-snapshot:latest # ruby-head (nightly snapshot build)
                - circleci/jruby:9.2

      - cc-upload-coverage:
          requires:
            - spec-circleci/ruby:2.4
            - spec-circleci/ruby:2.5
            - spec-circleci/ruby:2.6
            - spec-circleci/ruby:2.7
            - spec-circleci/jruby:9.2
