version: 2.1

jruby_env: &jruby_env
  # By default we have 2 CPUs and 4GB ram available
  # https://circleci.com/docs/2.0/configuration-reference/#resource_class
  JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"

common_env: &common_env
  # CircleCI container has two cores, but Ruby can see 32 cores. So we
  # configure test-queue.
  # See https://github.com/tmm1/test-queue#environment-variables
  TEST_QUEUE_WORKERS: 2

executors:
  mri:
    parameters:
      version:
        type: string
    docker:
      - image: circleci/ruby:<< parameters.version >>
    environment:
      <<: *common_env

  jruby:
    parameters:
      version:
        type: string
        default: "9.2"
    docker:
      - image: circleci/jruby:<< parameters.version >>
    environment:
      <<: *common_env
      <<: *jruby_env

  head:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      <<: *common_env

  head-with-jit:
    docker:
      - image: rubocophq/circleci-ruby-snapshot:latest
    environment:
      RUBYOPT: '--jit'
      <<: *common_env

jobs:
  spec:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/tmp
      - run: bundle install
      - run:
          name: Run specs
          command: |
            ./tmp/cc-test-reporter before-build
            COVERAGE=true bundle exec rake spec
            ./tmp/cc-test-reporter format-coverage --output tmp/codeclimate.$CIRCLE_JOB.json
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.*.json

  ascii_spec:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake ascii_spec

  rubocop:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec rake internal_investigation
      - run:
          name: Check requiring libraries successfully
          # See https://github.com/rubocop-hq/rubocop/pull/4523#issuecomment-309136113
          command: |
            ruby -I lib -r rubocop -e 'exit 0'

  # Job for downloading the Code Climate test reporter
  cc-setup:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      - run:
          name: Download Code Climate test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter

  # Job for merging code coverage results and sending them to Code Climate
  cc-upload-coverage:
    docker:
      - image: circleci/ruby:2.5
        environment:
          CC_TEST_REPORTER_ID: a11b66bfbb1acdf220d5cb317b2e945a986fd85adebe29a76d411ad6d74ec31f
    environment:
      <<: *common_env
    steps:
      - attach_workspace:
          at: ~/project/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json --parts 5 --output tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage --input tmp/codeclimate.total.json

  # Miscellaneous tasks
  documentation-checks:
    docker:
      - image: circleci/ruby:2.5
    environment:
      <<: *common_env
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Check documentation syntax
          command: bundle exec rake documentation_syntax_check
      - run:
          name: Build documentation and check that manual files are in sync
          command: bundle exec rake generate_cops_documentation

workflows:
  version: 2
  build:
    jobs:
      - documentation-checks
      - cc-setup

      # Ruby 2.2
      - spec:
          name: ruby-2.2-spec
          executor:
            name: mri
            version: "2.2"
          requires:
            - cc-setup
      - ascii_spec:
          name: ruby-2.2-ascii_spec
          executor:
            name: mri
            version: "2.2"
      - rubocop:
          name: ruby-2.2-rubocop
          executor:
            name: mri
            version: "2.2"

      # Ruby 2.3
      - spec:
          name: ruby-2.3-spec
          executor:
            name: mri
            version: "2.3"
          requires:
            - cc-setup
      - ascii_spec:
          name: ruby-2.3-ascii_spec
          executor:
            name: mri
            version: "2.3"
      - rubocop:
          name: ruby-2.3-rubocop
          executor:
            name: mri
            version: "2.3"

      # Ruby 2.4
      - spec:
          name: ruby-2.4-spec
          executor:
            name: mri
            version: "2.4"
          requires:
            - cc-setup
      - ascii_spec:
          name: ruby-2.4-ascii_spec
          executor:
            name: mri
            version: "2.4"
      - rubocop:
          name: ruby-2.4-rubocop
          executor:
            name: mri
            version: "2.4"

      # Ruby 2.5
      - spec:
          name: ruby-2.5-spec
          executor:
            name: mri
            version: "2.5"
          requires:
            - cc-setup
      - ascii_spec:
          name: ruby-2.5-ascii_spec
          executor:
            name: mri
            version: "2.5"
      - rubocop:
          name: ruby-2.5-rubocop
          executor:
            name: mri
            version: "2.5"

      # ruby-head (nightly snapshot build)
      - spec:
          name: ruby-head-spec
          executor:
            name: head
          requires:
            - cc-setup
      - ascii_spec:
          name: ruby-head-ascii_spec
          executor:
            name: head
      - rubocop:
          name: ruby-head-rubocop
          executor:
            name: head
      # With JIT compiler enabled!
      - spec:
          name: ruby-head-spec-with-jit
          executor:
            name: head-with-jit
          requires:
            - cc-setup
      - rubocop:
          name: ruby-head-rubocop-with-jit
          executor:
            name: head-with-jit

      # JRuby 9.2
      - spec:
          name: jruby-9.2-spec
          executor:
            name: jruby
          requires:
            - cc-setup
      - ascii_spec:
          name: jruby-9.2-ascii_spec
          executor:
            name: jruby
      - rubocop:
          name: jruby-9.2-rubocop
          executor:
            name: jruby

      - cc-upload-coverage:
          requires:
            - ruby-2.2-spec
            - ruby-2.3-spec
            - ruby-2.4-spec
            - ruby-2.5-spec
            - jruby-9.2-spec
