version: 2

steps: &steps
  steps:
    - checkout
    - run: bundle install
    - run: ruby .ci.rb

jobs:

  # Ruby 2.2
  ruby-2.2-spec:
    docker:
      - image: circleci/ruby:2.2
    environment:
      TASK: "spec"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  ruby-2.2-ascii_spec:
    docker:
      - image: circleci/ruby:2.2
    environment:
      TASK: "ascii_spec"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  ruby-2.2-rubocop:
    docker:
      - image: circleci/ruby:2.2
    environment:
      TASK: "internal_investigation"
      TEST_QUEUE_WORKERS: 2
    <<: *steps

  # Ruby 2.3
  ruby-2.3-spec:
    docker:
      - image: circleci/ruby:2.3
    environment:
      TASK: "spec"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  ruby-2.3-ascii_spec:
    docker:
      - image: circleci/ruby:2.3
    environment:
      TASK: "ascii_spec"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  ruby-2.3-rubocop:
    docker:
      - image: circleci/ruby:2.3
    environment:
      TASK: "internal_investigation"
      TEST_QUEUE_WORKERS: 2
    <<: *steps

  # Ruby 2.4
  ruby-2.4-spec:
    docker:
      - image: circleci/ruby:2.4
    environment:
      TASK: "spec"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  ruby-2.4-ascii_spec:
    docker:
      - image: circleci/ruby:2.4
    environment:
      TASK: "ascii_spec"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  ruby-2.4-rubocop:
    docker:
      - image: circleci/ruby:2.4
    environment:
      TASK: "internal_investigation"
      TEST_QUEUE_WORKERS: 2
    <<: *steps

  # Ruby 2.5
  ruby-2.5-spec:
    docker:
      - image: circleci/ruby:2.5
    environment:
      TASK: "spec"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  ruby-2.5-ascii_spec:
    docker:
      - image: circleci/ruby:2.5
    environment:
      TASK: "ascii_spec"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  ruby-2.5-rubocop:
    docker:
      - image: circleci/ruby:2.5
    environment:
      TASK: "internal_investigation"
      TEST_QUEUE_WORKERS: 2
    <<: *steps

  # JRuby 9.2
  jruby-9.2-spec:
    docker:
      - image: circleci/jruby:9.2
    environment:
      TASK: "spec"
      JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  jruby-9.2-ascii_spec:
    docker:
      - image: circleci/jruby:9.2
    environment:
      TASK: "ascii_spec"
      JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    <<: *steps
  jruby-9.2-rubocop:
    docker:
      - image: circleci/jruby:9.2
    environment:
      TASK: "internal_investigation"
      JRUBY_OPTS: "--debug -J-Xmn1024m -J-Xms2048m -J-Xmx2048m"
      TEST_QUEUE_WORKERS: 2
    <<: *steps

workflows:
  version: 2
  build:
    jobs:
      - ruby-2.2-spec
      - ruby-2.2-ascii_spec
      - ruby-2.2-rubocop
      - ruby-2.3-spec
      - ruby-2.3-ascii_spec
      - ruby-2.3-rubocop
      - ruby-2.4-spec
      - ruby-2.4-ascii_spec
      - ruby-2.4-rubocop
      - ruby-2.5-spec
      - ruby-2.5-ascii_spec
      - ruby-2.5-rubocop
      - jruby-9.2-spec
      - jruby-9.2-ascii_spec
      - jruby-9.2-rubocop
