# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.

inherit_from:
  - enabled.yml
  - disabled.yml

# Common configuration.
AllCops:
  # Include gemspec and Rakefile
  Includes:
    - '**/*.gemspec'
    - '**/Rakefile'
  Excludes: []

# Limit lines to 79 characters.
LineLength:
  Max: 79

# Avoid methods longer than 10 lines of code
MethodLength:
  CountComments: false  # count full line comments?
  Max: 10

# Avoid parameter lists longer than five parameters.
ParameterLists:
  Max: 5
  CountKeywordArgs: true

# Don't use semicolons to terminate expressions.
Semicolon:
  # For example; def area(height, width); height * width end
  AllowAfterParameterListInOneLineMethods: false
  # For example; def area(height, width) height * width; end
  AllowBeforeEndInOneLineMethods: true

# Avoid single-line methods.
SingleLineMethods:
  AllowIfMethodIsEmpty: true

# Use spaces inside hash literal braces - or don't.
SpaceInsideHashLiteralBraces:
  EnforcedStyleIsWithSpaces: true

# Symbol literals should use snake_case.
SymbolName:
  AllowCamelCase: true

# Avoid more than `Max` levels of nesting.
BlockNesting:
  Max: 3

# Use %r for regular expressions matching more than `MaxSlashes` '/'
# characters.
# Use %r only for regular expressions matching more than `MaxSlashes` '/'
# character.
RegexpLiteral:
  MaxSlashes: 1

# Align with the style guide.
CollectionMethods:
  PreferredMethods:
    collect: 'map'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

# Muli-line method chaining should be done with leading dots.
DotPosition:
  Style: 'leading'

# TrivialAccessors doesn't require exact name matches and doesn't allow predicated methods by default.
TrivialAccessors:
  ExactNameMatch: false
  AllowPredicates: false

# Allow safe assignment in conditions.
AssignmentInCondition:
  AllowSafeAssignment: true

# Allow safe assignment in conditions.
ParenthesesAroundCondition:
  AllowSafeAssignment: true

# Checks formatting of special comments
CommentAnnotation:
  Keywords:
    - TODO
    - FIXME
    - OPTIMIZE
    - HACK
    - REVIEW
