# These are all the cops that are disabled in the default configuration.

MethodCalledOnDoEndBlock:
  Description: 'Avoid chaining a method call on a do...end block.'
  Enabled: false

SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: false

TernaryOperator:
  Description: >-
                 Avoid ternary operators (boolean ? true : false). Use
                 multi-line if instead to emphasize code branches.
  Enabled: false
