# These are all the cops that are disabled in the default configuration.

MethodCalledOnDoEndBlock:
  Description: 'Avoid chaining a method call on a do...end block.'
  Enabled: false

SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: false

MultilineAssignment:
  Description: 'Place multi-line values on new line and indent.'
  Enabled: false
