# These are all the cops that are disabled in the default configuration.

SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: false

MethodCalledOnDoEndBlock:
  Description: 'Forbid use of method calls at the end of do ... end blocks'
  Enabled: false
